mysql:
  image: mysql:5.7
  container_name: database
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: arizonatest
    MYSQL_DATABASE: arizonatest
    MYSQL_USER: arizonatest
    MYSQL_PASSWORD: arizonatest

php:
  image: mikechernev/php7-fpm-laravel
  container_name: php
  volumes:
    - .:/var/www/html/arizonatest
  links:
    - mysql

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80